### ISSUE TITLE
Webpage not available (Фонд рабочей академии, API 28)

### ISSUE THREAD

**Issue by rt1shnik** [TimofeySin/RedRadioFRA#2]
Страница фонда рабочей академии не отображается на Android 9 (API level 28).

![ФРА](https://user-images.githubusercontent.com/4016063/72611103-42cf7500-393a-11ea-83de-ba3f3ebca878.png)

**Comment by TimofeySin** [comment]
Это из-за http и javascripta, исправил

**Comment by rt1shnik** [comment]
@TimofeySin 
По-прежнему не работает.
